# -*- coding: utf-8 -*-
"""CNN_CIFAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsD7ZgowXnR13S6XeqS5NNu3CwhzA5Hn
"""

pip install tensorflow

# Step 1: Import required libraries
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt

"""checking the data

CIFAR-10 is a famous image dataset with:
60,000 color images (32×32)
10 classes (car, dog, cat, plane, etc.)
"""

print("Loading CIFAR-10 dataset...")
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

"""Neural networks work better with:

floating point numbers (float32)
"""

x_train = x_train.astype('float32') / 255.0
x_test  = x_test.astype('float32')  / 255.0

"""After dividing by 255:
So now all pixel values are in the range:[0, 1]

Normalization (Feature Scaling)
Specifically:
Min–Max Normalization to range [0,1]
(because of this it will work fast,Improves model stability and accuracy)
"""



"""now we will do the one-hot encoding


It converts class numbers into one-hot vectors.==to_categorical
"""

y_train = to_categorical(y_train, 10)

y_test  = to_categorical(y_test,  10)

print(f"Training data shape: {x_train.shape}")   # (50000, 32, 32, 3)

print(f"Test data shape:     {x_test.shape}")    # (10000, 32, 32, 3)



"""Select  the labels and as it is store in list the label has it own index values so it will work when model predictions any index value that index value will represent the label name"""

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',

               'dog', 'frog', 'horse', 'ship', 'truck']



"""Convolution → Normalization → Convolution → Normalization → Pooling → Dropout"""

model = models.Sequential([

    # First Convolutional Block
    #2D convolution for images. "number of filters (feature maps)","filter size"
    layers.Conv2D               (32, (                             3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),

#Batch Normalization (Regularization + Optimization aid)
    #Normalizes outputs of previous layer
    #Keeps mean ≈ 0 and variance ≈ 1
    layers.BatchNormalization(),

    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),

    layers.BatchNormalization(),

  #Reduces image size by taking maximum value from each 2×2 block
    layers.MaxPooling2D((2, 2)),
#Prevents overfitting
    layers.Dropout(0.25),

    # Second Convolutional Block

    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),

    layers.BatchNormalization(),

    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),

    layers.BatchNormalization(),

    layers.MaxPooling2D((2, 2)),

    layers.Dropout(0.25),

    # Flatten and Dense layers

    layers.Flatten(),

    layers.Dense(512, activation='relu'),

    layers.BatchNormalization(),

    layers.Dropout(0.5),

      # Output layer – 10 classes

    layers.Dense(10, activation='softmax')

])



"""Adam = Adaptive Moment Estimations
Adjusts learning rate automatically
"""

model.compile(optimizer='adam',
            #It tells how wrong your model is.
              loss='categorical_crossentropy',

              metrics=['accuracy'])

model.summary()   # Print model architecture



print("\nTraining the model...")

history = model.fit(x_train, y_train,

                    epochs=20,               # increase to 30–50 for better results

                    batch_size=128,

                    validation_data=(x_test, y_test),

                    verbose=1)

# Step 7: Evaluate on test set
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print(f"\nTest accuracy: {test_acc:.4f}  ({test_acc*100:.2f}%)")



plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.tight_layout()
plt.show()



# Step 9: Make predictions on a few test images (visual check)

num_images = 8

predictions = model.predict(x_test[:num_images])

predicted_classes = np.argmax(predictions, axis=1)

true_classes = np.argmax(y_test[:num_images], axis=1)



plt.figure(figsize=(15, 8))

for i in range(num_images):

    plt.subplot(2, 4, i+1)

    plt.imshow(x_test[i])

    plt.title(f"Pred: {class_names[predicted_classes[i]]}\nTrue: {class_names[true_classes[i]]}",

              color=("green" if predicted_classes[i] == true_classes[i] else "red"))

    plt.axis('off')

plt.tight_layout()

plt.show()

# Optional: Save the model

# model.save("basic_cifar10_cnn.h5")

#print("Practical 1 completed.")

